version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8087:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: mhealy6
      DOCKER_INFLUXDB_INIT_PASSWORD: securepassword
      DOCKER_INFLUXDB_INIT_ORG: org
      DOCKER_INFLUXDB_INIT_BUCKET: metrics

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER: admin
      - GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana

  producer:
    build: ./kafka_producer
    container_name: kafka_producer
    depends_on:
       - kafka
    environment:
       - KAFKA_BROKER: kafka:9092
       - KAFKA_TOPIC: metrics
    
  consumer:
    build: ./kafka_consumer
    container_name: kafka_consumer
    depends_on:
      - kafka
      - influxdb
   environment:
      - KAFKA_BROKER: kafka:9092
      - KAFKA_TOPIC: metrics
      - INFLUXDB_URL: http://influxdb:8086
      - INFLUXDB_BUCKET: metrics
      - INFLUXDB_ORG: org
      - INFLUXDB_TOKEN: your_influxdb_token

volumes:
  influxdb-data:
  grafana-data:
